export const tasks = [
  {
    id: 1,
    title: "Complete Project Proposal",
    description: "Write and finalize project proposal document",
    priority: "High",
    dueDate: "2024-05-15",
    status: "in-progress",
  },
  {
    id: 2,
    title: "Prepare Presentation",
    description: "Create slides for project presentation",
    priority: "High",
    dueDate: "2024-05-20",
    status: "todo",
  },
  {
    id: 3,
    title: "Review Code",
    description: "Review and refactor code for better performance",
    priority: "Medium",
    dueDate: "2024-05-25",
    status: "todo",
  },
  {
    id: 4,
    title: "Meeting with Client",
    description: "Discuss project updates and requirements with the client",
    priority: "High",
    dueDate: "2024-05-18",
    status: "completed",
  },
  {
    id: 5,
    title: "Update Documentation",
    description: "Update project documentation with recent changes",
    priority: "Medium",
    dueDate: "2024-05-23",
    status: "in-progress",
  },
  {
    id: 6,
    title: "Fix Bugs",
    description: "Identify and fix any bugs in the application",
    priority: "High",
    dueDate: "2024-05-22",
    status: "todo",
  },
  {
    id: 7,
    title: "Code Refactoring",
    description: "Refactor codebase to improve maintainability",
    priority: "Medium",
    dueDate: "2024-05-27",
    status: "todo",
  },
  {
    id: 8,
    title: "Testing",
    description: "Perform comprehensive testing of the application",
    priority: "High",
    dueDate: "2024-05-30",
    status: "in-progress",
  },
  {
    id: 9,
    title: "Deploy to Production",
    description: "Deploy the application to production servers",
    priority: "High",
    dueDate: "2024-06-01",
    status: "todo",
  },
  {
    id: 10,
    title: "Client Feedback",
    description: "Gather feedback from the client on the latest changes",
    priority: "Medium",
    dueDate: "2024-05-28",
    status: "completed",
  },
];
